megasena:
  url: "http://www1.caixa.gov.br/loterias/loterias/megasena/megasena_pesquisa_new.asp"
  dom: "//span[@class='num_sorteio'][2]/ul/li"
quina:
  url: "http://www1.caixa.gov.br/loterias/loterias/quina/quina_pesquisa_new.asp"
  dom: "//span[@id='sorteio2']/ul/li"
# duplasena:
#   url: "http://www1.caixa.gov.br/loterias/loterias/duplasena/duplasena_pesquisa_new.asp"
#   dom: ""
# instantanea:
#   url: ""
#   dom: ""
# federal:
#   url: ""
#   dom: ""
# loteca:
#   url: "http://www1.caixa.gov.br/loterias/loterias/loteca/loteca_pesquisa_new.asp"
#   dom: ""
# lotofacil:
#   url: "http://www1.caixa.gov.br/loterias/loterias/lotofacil/lotofacil_pesquisa_new.asp"
#   dom: ""
# lotomania:
#   url: ""
#   dom: ""
# lotogol:
#   url: "http://www1.caixa.gov.br/loterias/loterias/lotogol/lotogol_pesquisa_new.asp"
#   dom: ""
# timemania:
#   url: ""
#   dom: ""
