# lotofacil:
#   url: ""
#   dom: ""
# lotomania:
#   url: ""
#   dom: ""
# lotogol:
#   url: ""
#   dom: ""
# loteca:
#   url: ""
#   dom: ""
# timemania:
#   url: ""
#   dom: ""
# federal:
#   url: ""
#   dom: ""
# instantanea:
#   url: ""
#   dom: ""
quina:
  url: "http://www1.caixa.gov.br/loterias/loterias/quina/quina_pesquisa_new.asp"
  dom: "//span[@id='sorteio2']/ul/li"
# duplasena:
#   url: ""
#   dom: ""
megasena:
  url: "http://www1.caixa.gov.br/loterias/loterias/megasena/megasena_pesquisa_new.asp"
  dom: "//body/span[@class='num_sorteio'][2]/ul/li"
